language: cpp

dist: focal

install:
  - pip install conan
  - conan profile new default --detect
  - conan profile update settings.compiler.libcxx=libstdc++11 default

env:
  jobs:
    - BUILD_CONFIGURATION=Release
    - BUILD_CONFIGURATION=Debug

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DMUPDF_WRAPPER_ENABLE_TEST=ON ..
  - cmake --build .
  - ctest --verbose
